// <auto-generated />
using System;
using Groupe3GestionEnseignant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Groupe3GestionEnseignant.Migrations
{
    [DbContext(typeof(Groupe3GestionEnseingnantDbContext))]
    [Migration("20240315020214_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Absence", b =>
                {
                    b.Property<int>("IdAbscent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbscent"));

                    b.Property<int?>("EtudiantMatricule")
                        .HasColumnType("int");

                    b.Property<DateTime>("Jour")
                        .HasColumnType("datetime2");

                    b.Property<int>("Matricule")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAbscent");

                    b.HasIndex("EtudiantMatricule");

                    b.ToTable("Absence");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.CahierDeTexte", b =>
                {
                    b.Property<int>("IdCahierTexte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCahierTexte"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCahierTexte");

                    b.ToTable("CahierDeTexte");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EtudiantMatricule")
                        .HasColumnType("int");

                    b.Property<int>("Matricule")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClasse");

                    b.HasIndex("EtudiantMatricule");

                    b.ToTable("Classe");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Cour", b =>
                {
                    b.Property<int>("IdCour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCour"));

                    b.Property<int?>("ClasseIdClasse")
                        .HasColumnType("int");

                    b.Property<int?>("EnseignantIdEnseignant")
                        .HasColumnType("int");

                    b.Property<string>("Horaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdClasse")
                        .HasColumnType("int");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCour");

                    b.HasIndex("ClasseIdClasse");

                    b.HasIndex("EnseignantIdEnseignant");

                    b.ToTable("Cour");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnseignant"));

                    b.Property<int>("MotPasse")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnseignant");

                    b.ToTable("Enseignant");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Etudiant", b =>
                {
                    b.Property<int>("Matricule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matricule"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricule");

                    b.ToTable("Etudiant");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Saisir", b =>
                {
                    b.Property<DateTime>("Jour")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CahierDeTexteIdCahierTexte")
                        .HasColumnType("int");

                    b.Property<int?>("EnseignantIdEnseignant")
                        .HasColumnType("int");

                    b.Property<int>("IdCahierTexte")
                        .HasColumnType("int");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.HasKey("Jour");

                    b.HasIndex("CahierDeTexteIdCahierTexte");

                    b.HasIndex("EnseignantIdEnseignant");

                    b.ToTable("Saisir");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Absence", b =>
                {
                    b.HasOne("Groupe3GestionEnseignant.Models.ENTITE.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantMatricule");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Classe", b =>
                {
                    b.HasOne("Groupe3GestionEnseignant.Models.ENTITE.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantMatricule");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Cour", b =>
                {
                    b.HasOne("Groupe3GestionEnseignant.Models.ENTITE.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseIdClasse");

                    b.HasOne("Groupe3GestionEnseignant.Models.ENTITE.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantIdEnseignant");

                    b.Navigation("Classe");

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("Groupe3GestionEnseignant.Models.ENTITE.Saisir", b =>
                {
                    b.HasOne("Groupe3GestionEnseignant.Models.ENTITE.CahierDeTexte", "CahierDeTexte")
                        .WithMany()
                        .HasForeignKey("CahierDeTexteIdCahierTexte");

                    b.HasOne("Groupe3GestionEnseignant.Models.ENTITE.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantIdEnseignant");

                    b.Navigation("CahierDeTexte");

                    b.Navigation("Enseignant");
                });
#pragma warning restore 612, 618
        }
    }
}
